### ISSUE TITLE
Decide the base project

### ISSUE THREAD

**Issue by mirayiyidogan** [dogukanarslan/SWE574-Group-3#12]
In order to decide the base project, we will prepare our previous projects with their pros & cons to compare it with our stakeholders requirements (@uskudarli)

**Comment by mirayiyidogan** [comment]
Dogukan's Project:

-Missing images
-Space feature is needed
-Label/tag is missing 

**Mongo, Node.js, EJS

**Comment by mirayiyidogan** [comment]
Miray's Project:

-Space needs to be developed in detail
-Label/tag is missing
-Friends/follower system is missing

**Comment by mirayiyidogan** [comment]
İlayda's Project:

-Space feature is already developed
-Friends/follower system and tag is ready
-Need to work on UI/UX 

*PostgreSQL, Django,

**Comment by mirayiyidogan** [comment]
Afize's Project:

-Image is missing
-Search feature needs to be evalueated
-Follow/friend feature is already developed
-Like is missing

**Django, MySQL

**Comment by mirayiyidogan** [comment]
Its been decided to continue on İlayda's project :)

**Comment by cansincomert** [comment]
Issue closed as #14
