### ISSUE TITLE
Ask Annotation Mechanism and analyze it.

### ISSUE THREAD

**Issue by ilaydakurtboun** [dogukanarslan/SWE574-Group-3#24]

**Comment by afize1** [comment]
**Functional Requirements**
1. The system shall allow to add comments as annotation.
2. The system shall allow highlight selected parts of the post or post comment by user. The system shall enable to show when the comment as annotation is added, and by who.
3. The system shall enable to be answered comments by user.
4. The system shall enable to add comments as annotation which is linked to the highlighted parts of the post.
5. The system shall allow adding comments as links and text as annotation.
6. The system shall enable to show existing annotations.
7. The system shall enable to be removed highlighted parts or comments by owner of annotations.
8. The system shall enable to keep annotations.
9. The system shall enable to display kept annotations in the post page.

**Non-Functional Requirements**
1. The system shall meet w3c web annotation standards.

@emreberk92 please check requirements :)
