### ISSUE TITLE
Review Requirements

### ISSUE THREAD

**Issue by ilaydakurtboun** [dogukanarslan/SWE574-Group-3#28]
https://github.com/dogukanarslan/SWE574-Group-3/wiki/Requirements-Specification

**Comment by uskudarli** [comment]
Thanks. Here are some comments...

There are related parts, however there are some improvements needed. Some are related to specification itself. Some are related to the requirements. I am not sure if the requirements are understood. 

Can you please read the following and let me know after you have made revisions?

1. `Any user shall create new space.`   -- actually registered users can. Also, you should state what the user must provide to create spaces.
2. `Public spaces shall be accessible via a search.`
3. `Spaces shall serve as a common interest / topic sharing platform.`   -- this is not a requirement specification.   It is a desirable property of the system. It is better expressed in the overview/scope of the system. 
4. `The system should get the words and their codes from Wikidata as semantic tag.`  -- unclear. Define semantic tag in the glossary and then in specification state what the user must provide for functionality.

Please rewrite the specifications clearly (articulate which users need to provide what information to achieve the taks). 

Also, write a **glossary** that defines key terms. You can use the glossary terms in your requirements.
