### ISSUE TITLE
Create milestones

### ISSUE THREAD

**Issue by Egelas** [dogukanarslan/SWE574-Group-3#29]

**Comment by mirayiyidogan** [comment]
**There will be x milestone**

1. Milestone 1 (27/03/2023) : Unique link, user search, user roles and permissions, space join
2. Milestone 2 (10/04/2023) : Text Annotation, Badge, Sementatic Tag, Recommandation, Report 
3. Milestone 3 (24/04/2023) : Search(tag), Image Annotation
4. Milestone 4 (08/05/2023) : Test

**Comment by Egelas** [comment]
[Milestones](https://github.com/dogukanarslan/SWE574-Group-3/milestones)
