### ISSUE TITLE
Mockup Updates

### ISSUE THREAD

**Issue by ilaydakurtboun** [dogukanarslan/SWE574-Group-3#32]
If there is any changes after writing requirements, please update related mockups. If not, you can mark as done:
- [x] Space @cansincomert 
- [x] Badge @mirayiyidogan 
- [x] Semantic Tag @ilaydakurtboun 
- [x] Search @dogukanarslan 
- [x] Annotation @afize1 @emreberk92 
- [x] Recommandation @samedtorunn

**Comment by afize1** [comment]
- [ ] Annotation mockup for image is created and added to wiki page.
- [ ] Annotation mockup for text mockup is updated.
- [ ] After determining data model, the details will be added to annotation mockups.

**Comment by ilaydakurtboun** [comment]
Semantic tag adding and searching mock ups are updated on [wiki page](https://github.com/dogukanarslan/SWE574-Group-3/wiki/Mockups)
