### ISSUE TITLE
Do Mockups (Conceptual) 

### ISSUE THREAD

**Issue by Egelas** [dogukanarslan/SWE574-Group-3#7]
and add it to [our Wiki](https://github.com/dogukanarslan/SWE574-Group-3/wiki/Mockups)

**Comment by dogukanarslan** [comment]
We can use [figma](https://www.figma.com/) to generate mockups

**Comment by mirayiyidogan** [comment]
I will work on Badge Mockup and related features

**Comment by cansincomert** [comment]
@afize1 Annotations mock-up

**Comment by cansincomert** [comment]
Semantic tagging - Recommendation mock-up

**Comment by afize1** [comment]
annotations mockup done!
Url:https://www.figma.com/file/5G1jhKCVgR3D3jv72m169O/Swe574?node-id=0%3A1&t=ddZx8wmTGlWORilr-1
![9656A9DC-F38D-478F-9A55-7962D5BC3713](https://user-images.githubusercontent.com/115039188/222955637-6eabe0d3-f98e-4569-b3e6-bc1415f5a98f.jpeg)

**Comment by ilaydakurtboun** [comment]
Creating Semantic Tag Mock Ups is done.

**Comment by cansincomert** [comment]
Enhancement of space is done.
[https://www.figma.com/file/KuVfJpnYeuhypOOf5QbVud/Space-Page?node-id=0%3A1&t=HQgU1DffPYDL0lKa-1]

**Comment by samedtorunn** [comment]
Space recommendation

![Image](https://user-images.githubusercontent.com/33091148/223165670-54a2086e-d921-4248-9853-2bdb1546ed4f.png)
